graph TD
    Configuração --> Controladores
    Controladores --> Casos_de_Uso
    Casos_de_Uso --> Repositórios
    Repositórios --> Persistência
    Persistência --> DTOs_e_Mapeamento
    DTOs_e_Mapeamento --> Exceções
