spring.application.name=fortaleza.sabor

# datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fortaleza
spring.datasource.username=postgres
spring.datasource.password=postgres

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialização do SQL
spring.sql.init.mode=always